version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    # depends_on:
    #   - backend

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=your_password
  #     - MYSQL_DB=online_documents
  #     - REDIS_HOST=redis
  #   depends_on:
  #     - mysql
  #     - redis

  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: your_password
  #     MYSQL_DATABASE: online_documents
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend

# volumes:
#   mysql-data: