version: '3.8'

services:
  frontend:
    build: ./frontend
    # ports:
    #   - "3000:80"
    volumes:
    - ./frontend/src:/app/src
    - ./frontend/public:/app/public
    - ./frontend/package.json:/app/package.json
    - ./frontend/webpack.config.js:/app/webpack.config.js
    - ./frontend/tsconfig.json:/app/tsconfig.json
    ports:
      - 3000:3000
    command: [nodemon, start, --ext, js,jsx,ts,tsx,html,css, --exec, npm, start]
    # depends_on:
    #   - backend

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=your_password
  #     - MYSQL_DB=online_documents
  #     - REDIS_HOST=redis
  #   depends_on:
  #     - mysql
  #     - redis

  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: your_password
  #     MYSQL_DATABASE: online_documents
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend

# volumes:
#   mysql-data: